 #EXTINF:-1 1,http://cdn.adultiptv.net/livecams.m3u8
 #EXTINF:-1 2,http://cdn.adultiptv.net/anal.m3u8
 #EXTINF:-1 3,http://cdn.adultiptv.net/bigass.m3u8
 #EXTINF:-1 4,http://cdn.adultiptv.net/bigdick.m3u8
 #EXTINF:-1 5,http://cdn.adultiptv.net/bigtits.m3u8
 #EXTINF:-1 6,http://cdn.adultiptv.net/blonde.m3u8
 #EXTINF:-1 7,http://cdn.adultiptv.net/blowjob.m3u8
 #EXTINF:-1 8,http://cdn.adultiptv.net/brunette.m3u8
 #EXTINF:-1 9,http://cdn.adultiptv.net/compilation.m3u8
 #EXTINF:-1 10,http://cdn.adultiptv.net/cuckold.m3u8
 #EXTINF:-1 11,http://cdn.adultiptv.net/fetish.m3u8
 #EXTINF:-1 12,http://cdn.adultiptv.net/gangbang.m3u8
 #EXTINF:-1 13,http://cdn.adultiptv.net/gay.m3u8
 #EXTINF:-1 14,http://cdn.adultiptv.net/hardcore.m3u8
 #EXTINF:-1 15,http://cdn.adultiptv.net/interracial.m3u8
 #EXTINF:-1 16,http://cdn.adultiptv.net/latina.m3u8
 #EXTINF:-1 17,http://cdn.adultiptv.net/lesbian.m3u8
 #EXTINF:-1 18,http://cdn.adultiptv.net/milf.m3u8
 #EXTINF:-1 19,http://cdn.adultiptv.net/pornstar.m3u8
 #EXTINF:-1 20,http://cdn.adultiptv.net/pov.m3u8
 #EXTINF:-1 21,http://cdn.adultiptv.net/rough.m3u8
 #EXTINF:-1 22,http://cdn.adultiptv.net/russian.m3u8
 #EXTINF:-1 23,http://cdn.adultiptv.net/teen.m3u8
 #EXTINF:-1 24,http://cdn.adultiptv.net/threesome.m3u8
