#EXTM3U
#EXTINF:-1 tvg-id="106" tvg-name="CCTV4K" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV4k.png" group-title="央视",CCTV4K
http://223.110.236.8/ott.js.chinamobile.com/PLTV/3/224/3221228242/index.m3u8
#EXTINF:-1 tvg-id="106" tvg-name="CCTV4K" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV4k.png" group-title="央视",CCTV4K 1080P
http://liveop.cctv.cn/hls/4KHD/playlist.m3u8
#EXTINF:-1 tvg-id="1" tvg-name="CCTV1" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png" group-title="央视",CCTV1
http://coocaa-ynbit-ws.ifengli.com:2386/live/cctv-1hd/1.m3u8
#EXTINF:-1 tvg-id="1" tvg-name="CCTV1" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV1.png" group-title="央视",CCTV1
http://39.134.39.39/TVOD/88888888/224/3221226247/index.m3u8


#EXTINF:-1 tvg-id="2" tvg-name="CCTV2" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV2.png" group-title="央视",CCTV2
http://39.134.19.8/dbiptv.sn.chinamobile.com/PLTV/88888888/224/3221226195/1.m3u8
#EXTINF:-1 tvg-id="3" tvg-name="CCTV3" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV3.png" group-title="央视",CCTV3
http://coocaa-ynbit-ws.ifengli.com:2386/live/cctv-3hd/1.m3u8
#EXTINF:-1 tvg-id="4" tvg-name="CCTV4" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV4.png" group-title="央视",CCTV4
http://39.134.19.1/dbiptv.sn.chinamobile.com/PLTV/88888888/224/3221226191/1.m3u8
#EXTINF:-1 tvg-id="5" tvg-name="CCTV5" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV5.png" group-title="央视",CCTV5
http://39.134.39.39/PLTV/88888888/224/3221226224/index.m3u8
#EXTINF:-1 tvg-id="6" tvg-name="CCTV5+" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV5+.png" group-title="央视",CCTV5+
http://39.135.138.60:18890/PLTV/88888910/224/3221225649/index.m3u8
#EXTINF:-1 tvg-id="7" tvg-name="CCTV6" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV6.png" group-title="央视",CCTV6
http://39.134.39.39/TVOD/88888888/224/3221226226/index.m3u8
#EXTINF:-1 tvg-id="7" tvg-name="CCTV6" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV6.png" group-title="电影",CCTV6
http://39.134.39.39/TVOD/88888888/224/3221226226/index.m3u8
#EXTINF:-1 tvg-id="8" tvg-name="CCTV7" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV7.png" group-title="央视",CCTV7
http://39.134.66.66/PLTV/88888888/224/3221225671/index.m3u8
#EXTINF:-1 tvg-id="9" tvg-name="CCTV8" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV8.png" group-title="央视",CCTV8
http://39.135.138.58:18890/PLTV/88888888/224/3221225635/index.m3u8
#EXTINF:-1 tvg-id="10" tvg-name="CCTV9" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV9.png" group-title="央视",CCTV9
http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225734/index.m3u8
#EXTINF:-1 tvg-id="11" tvg-name="CCTV10" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV10.png" group-title="央视",CCTV10
http://39.134.66.66/PLTV/88888888/224/3221225677/index.m3u8
#EXTINF:-1 tvg-id="12" tvg-name="CCTV11" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV11.png" group-title="央视",CCTV11
http://39.135.138.59:18890/PLTV/88888910/224/3221225628/index.m3u8
#EXTINF:-1 tvg-id="13" tvg-name="CCTV12" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV12.png" group-title="央视",CCTV12
http://ottrrs.hl.chinamobile.com/PLTV/88888888/224/3221225731/index.m3u8
#EXTINF:-1 tvg-id="14" tvg-name="CCTV13" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV13.png" group-title="央视",CCTV13
http://ott.js.chinamobile.com/PLTV/4/224/3221228121/index.m3u8
#EXTINF:-1 tvg-id="15" tvg-name="CCTV14" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV14.png" group-title="央视",CCTV14
http://39.134.66.66/PLTV/88888888/224/3221225674/index.m3u8
#EXTINF:-1 tvg-id="16" tvg-name="CCTV15" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV15.png" group-title="央视",CCTV15
http://39.135.138.58:18890/PLTV/88888888/224/3221225641/index.m3u8
#EXTINF:-1 tvg-id="16" tvg-name="CCTV16" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV16.png" group-title="央视",CCTV16
http://liveop.cctv.cn/hls/CCTV16HD/playlist.m3u8
#EXTINF:-1 tvg-id="17" tvg-name="CCTV17" tvg-logo="http://epg.51zmt.top:8000/tb1/CCTV/CCTV17.png" group-title="央视",CCTV17
http://39.134.115.163:8080/PLTV/88888910/224/3221225908/index.m3u8
#EXTINF:-1 tvg-name="老故事" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E8%80%81%E6%95%85%E4%BA%8B.png" group-title="央视",老故事
http://39.134.18.68/dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226236/index.m3u8
#EXTINF:-1 tvg-name="中学生" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E4%B8%AD%E5%AD%A6%E7%94%9F.png" group-title="央视",中学生
http://39.135.140.227:6610/PLTV/88888888/224/3221225515/2/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="新科动漫" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E6%96%B0%E7%A7%91%E5%8A%A8%E6%BC%AB.png" group-title="央视",新科动漫
http://cctvtxyh5ca.liveplay.myqcloud.com/live/xinkedongman_2/index.m3u8
#EXTINF:-1 tvg-name="发现之旅" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E5%8F%91%E7%8E%B0%E4%B9%8B%E6%97%85.png" group-title="央视",发现之旅
http://223.110.241.137:6610/gitv/live1/G_FAXIANZL/G_FAXIANZL/.m3u8
#EXTINF:-1 tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E5%8D%AB%E7%94%9F%E5%81%A5%E5%BA%B7.png" group-title="央视",CCTV 卫生健康
#EXTINF:-1 tvg-name="第一剧场" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E7%AC%AC%E4%B8%80%E5%89%A7%E5%9C%BA.png" group-title="央视",CCTV 第一剧场
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226124/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="怀旧剧场" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E6%80%80%E6%97%A7%E5%89%A7%E5%9C%BA.png" group-title="央视",CCTV 怀旧剧场
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226097/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="风云剧场" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E9%A3%8E%E4%BA%91%E5%89%A7%E5%9C%BA.png" group-title="央视",CCTV 风云剧场
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226107/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="风云音乐" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E9%A3%8E%E4%BA%91%E9%9F%B3%E4%B9%90.png" group-title="央视",CCTV 风云音乐
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226083/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="女性时尚" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E5%A5%B3%E6%80%A7%E6%97%B6%E5%B0%9A.png" group-title="央视",CCTV 女性时尚
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226104/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="兵器科技" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E5%85%B5%E5%99%A8%E7%A7%91%E6%8A%80.png" group-title="央视",CCTV 兵器科技
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226111/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="世界地理" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E4%B8%96%E7%95%8C%E5%9C%B0%E7%90%86.png" group-title="央视",CCTV 世界地理
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226071/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="风云足球" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E8%B6%B3%E7%90%83%E9%A3%8E%E4%BA%91.png" group-title="央视",CCTV 风云足球
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226153/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="央视台球" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E5%A4%AE%E8%A7%86%E5%8F%B0%E7%90%83.png" group-title="央视",CCTV 央视台球
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226117/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-name="高尔夫网球" tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E9%AB%98%E5%B0%94%E5%A4%AB%C2%B7%E7%BD%91%E7%90%83.png" group-title="央视",CCTV 高尔夫网球
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226114/1/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/CCTV-%E7%94%B5%E8%A7%86%E6%8C%87%E5%8D%97.png" group-title="央视",CCTV 电视指南
http://39.136.18.76/cdnrrs.gz.chinamobile.com/PLTV/88888888/224/3221226120/1/index.m3u8?fmt=ts2hls




#EXTINF:-1 tvg-id="6245" tvg-name="CHC动作电影" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/CHC1.jpg" group-title="电影",CHC动作电影
http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226465/index.m3u8
#EXTINF:-1 tvg-id="6241" tvg-name="CHC高清电影" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/CHC3.jpg" group-title="电影",CHC高清电影
http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226463/index.m3u8
#EXTINF:-1 tvg-id="6246" tvg-name="CHC家庭电影" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/CHC2.jpg" group-title="电影",CHC家庭电影
http://dbiptv.sn.chinamobile.com/PLTV/88888890/224/3221226462/index.m3u8
#EXTINF:-1 tvg-id="30" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/beijing.png" group-title="电影",北京4K超清
http://beifeng.site:4000/udp/239.3.1.249:8001
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/beijing.png" group-title="电影",北京IPTV淘电影
http://39.134.134.85/otttv.bj.chinamobile.com/TVOD/88888888/224/3221226552/1.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/beijing.png" group-title="电影",北京IPTV淘娱乐
http://39.135.238.69/otttv.bj.chinamobile.com/TVOD/88888888/224/3221226551/1.m3u8

#EXTINF:-1 tvg-id="30" tvg-name="北京卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/beijing.png" group-title="卫视",北京卫视
http://39.134.39.39/PLTV/88888888/224/3221226161/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/beijing.png" group-title="卫视",北京冬奥
http://39.135.138.58:18890/PLTV/88888888/224/3221225676/index.m3u8
#EXTINF:-1 tvg-id="39" tvg-name="天津卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/tianjin.png" group-title="卫视",天津卫视
http://39.134.66.66/PLTV/88888888/224/3221225665/index.m3u8
#EXTINF:-1 tvg-id="31" tvg-name="东方卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/dongfang.png" group-title="卫视",东方卫视
http://39.134.39.39/PLTV/88888888/224/3221226155/index.m3u8
#EXTINF:-1 tvg-id="27" tvg-name="湖南卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/hunan.png" group-title="卫视",湖南卫视
http://124.232.233.17:6610/000000001001/201500000219/index.m3u8?IASHttpSessionId=SLB2046220190906022827233263&m3u8_level=2
#EXTINF:-1 tvg-id="48" tvg-name="湖北卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/hubei.png" group-title="卫视",湖北卫视
http://39.135.138.59:18890/PLTV/88888910/224/3221225740/index.m3u8
#EXTINF:-1 tvg-id="28" tvg-name="浙江卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/zhejiang.png" group-title="卫视",浙江卫视
http://223.110.243.173/PLTV/3/224/3221227215/index.m3u8
#EXTINF:-1 tvg-id="29" tvg-name="江苏卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/jiangsu.png" group-title="卫视",江苏卫视
http://39.134.39.39/PLTV/88888888/224/3221226157/index.m3u8
#EXTINF:-1 tvg-id="41" tvg-name="东南卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/dongnan.png" group-title="卫视",东南卫视
http://39.134.39.39/PLTV/88888888/224/3221226182/index.m3u8
#EXTINF:-1 tvg-id="38" tvg-name="山东卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/shandong.png" group-title="卫视",山东卫视
http://39.134.39.39/PLTV/88888888/224/3221226162/index.m3u8
#EXTINF:-1 tvg-id="32" tvg-name="安徽卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/anhui.png" group-title="卫视",安徽卫视
http://39.134.39.39/TVOD/88888888/224/3221226205/index.m3u8
#EXTINF:-1 tvg-id="43" tvg-name="广西卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/guangxi.png" group-title="卫视",广西卫视
http://39.135.138.58:18890/PLTV/88888888/224/3221226211/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-id="33" tvg-name="广东卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/guangdong.png" group-title="卫视",广东卫视
http://39.134.39.39/PLTV/88888888/224/3221226180/index.m3u8
#EXTINF:-1 tvg-id="60" tvg-name="南方卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/nanfang.png" group-title="广东",南方卫视
http://223.110.246.70/ott.js.chinamobile.com/PLTV/4/224/3221227005/index.m3u8
#EXTINF:-1 tvg-id="34" tvg-name="深圳卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/shenzhen.png" group-title="卫视",深圳卫视
http://39.134.39.39/PLTV/88888888/224/3221226199/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/guangdong.png" group-title="广东",广东体育
http://116.199.5.52:8114/00000000/index.m3u8?&Fsv_ctype=LIVES&Fsv_otype=1&FvSeid=5abd1660af1babb4&Fsv_filetype=1&Fsv_ctype=LIVES&Fsv_cid=0&Fsv_chan_hls_se_idx=8&Fsv_rate_id=0&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Provider_id=&Pcontent_id=&Fsv_CMSID=&Fsv_otype=1#https://nclive.grtn.cn/typd/sd/live.m3u8?_upt=07d322ea1595884800
#EXTINF:-1 tvg-id="7125" tvg-name="珠江频道" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/zhujiang.png" group-title="广东",广东珠江
http://116.199.5.52:8114/00000000/index.m3u8?&Fsv_ctype=LIVES&Fsv_otype=1&FvSeid=5abd1660af1babb4&Fsv_filetype=1&Fsv_ctype=LIVES&Fsv_cid=0&Fsv_chan_hls_se_idx=79&Fsv_rate_id=0&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Provider_id=&Pcontent_id=&Fsv_CMSID=&Fsv_otype=1
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/guangdong.png" group-title="广东",广东公共
http://116.199.5.51:8114/00000000/index.m3u8?&Fsv_ctype=LIVES&Fsv_otype=1&FvSeid=5abd1660af1babb4&Fsv_filetype=1&Fsv_ctype=LIVES&Fsv_cid=0&Fsv_chan_hls_se_idx=85&Fsv_rate_id=0&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Provider_id=&Pcontent_id=&Fsv_CMSID=&Fsv_otype=1
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/guangdong.png" group-title="广东",广东新闻
http://116.199.5.51:8114/00000000/index.m3u8?&Fsv_ctype=LIVES&Fsv_otype=1&FvSeid=5abd1660af1babb4&Fsv_filetype=1&Fsv_ctype=LIVES&Fsv_cid=0&Fsv_chan_hls_se_idx=84&Fsv_rate_id=0&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Provider_id=&Pcontent_id=&Fsv_CMSID=&Fsv_otype=1
#EXTINF:-1 tvg-logo="https://gitee.com/jackguo1982/iptv/raw/master/TVG-logo/%E5%B9%BF%E4%B8%9C%E5%B0%91%E5%84%BF.png" group-title="少儿",广东少儿


#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/ZH.jpg" group-title="广东",珠海1台
https://dslive.grtn.cn/zhzh/sd/live.m3u8?_upt=8665d5001623917283&auth_key=1623912026-0-0-85a6e25f9928f40ab21b2ef19b4a852a
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/ZSGG.jpg" group-title="广东",,中山公共
http://149.129.100.78/tv.php?id=zsgg
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/ZSGG.jpg" group-title="广东",,中山教育
http://149.129.100.78/tv.php?id=zsjy
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/ZSGG.jpg" group-title="广东",,中山综合
http://149.129.100.78/tv.php?id=zszh

#EXTINF:-1 tvg-id="36" tvg-name="辽宁卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/liaoning.png" group-title="卫视",辽宁卫视
http://39.134.39.39/PLTV/88888888/224/3221226209/index.m3u8
#EXTINF:-1 tvg-id="46" tvg-name="黑龙江卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/heilongjiang.png" group-title="卫视",黑龙江卫视
http://39.134.39.39/PLTV/88888888/224/3221226142/index.m3u8
#EXTINF:-1 tvg-id="50" tvg-name="江西卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/jiangxi.png" group-title="卫视",江西卫视
http://39.134.39.39/PLTV/88888888/224/3221226207/index.m3u8
#EXTINF:-1 tvg-id="47" tvg-name="河南卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/henan.png" group-title="卫视",河南卫视
http://39.135.138.58:18890/PLTV/88888888/224/3221225611/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-id="37" tvg-name="旅游卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/lvyou.png" group-title="卫视",海南卫视
http://hwrr.jx.chinamobile.com:8080/PLTV/88888888/224/3221226212/index.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-id="58" tvg-name="云南卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/yunnan.png" group-title="卫视",云南卫视
http://223.110.245.159/ott.js.chinamobile.com/PLTV/3/224/3221225838/index.m3u8
#EXTINF:-1 tvg-id="40" tvg-name="重庆卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/chongqing.png" group-title="卫视",重庆卫视
http://39.134.66.66/PLTV/88888888/224/3221225873/index.m3u8
#EXTINF:-1 tvg-id="42" tvg-name="甘肃卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/ws/gansu.png" group-title="卫视",甘肃卫视
http://39.134.39.39/PLTV/88888888/224/3221226240/index.m3u8


#EXTINF:-1 tvg-id="126" tvg-name="翡翠台" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/TVB翡翠台.png" group-title="港澳台",TVB翡翠台
http://zs178.3322.org:9081/stream/channelid/1009999176
#EXTINF:-1 tvg-id="126" tvg-name="翡翠台" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/TVB翡翠台.png" group-title="港澳台",TVB翡翠台备用
http://iptv.tvfix.org/hls/jade2.m3u8

#EXTINF:-1 tvg-id="131" tvg-name="TVB星河频道" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/TVB星河.png" group-title="港澳台",TVB 星河台 Xing He
http://50.7.161.82:8278/streams/d/Xinhe/playlist.m3u8
#EXTINF:-1 tvg-id="416" tvg-name="J2" tvg-logo="https://raw.githubusercontent.com/feng658know/m3u/main/tb/TVBJ2.jpg" group-title="港澳台",TVB J2
http://zs178.3322.org:9081/stream/channelid/465624710
#EXTINF:-1 tvg-id="127" tvg-name="明珠台" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/TVB明珠台.png" group-title="港澳台",明珠台
http://zs178.3322.org:9081/stream/channelid/761452529
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",TVB电视剧
https://edge6a.v2h-cdn.com/appt7/TDramaTV.stream_720p/playlist.m3u8
#EXTINF:-1 tvg-id="130" tvg-name="无线新闻" tvg-logo="https://raw.githubusercontent.com/feng658know/m3u/main/WXXW.jpg" group-title="港澳台",无线新闻
http://zs178.3322.org:9081/stream/channelid/247101656
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/tvb6.jpg" group-title="港澳台",无线财经
http://zs178.3322.org:9081/stream/channelid/363868794
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/RH31.jpg" group-title="港澳台",港台电视31
http://zs178.3322.org:9081/stream/channelid/991326153
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/RH32.jpg" group-title="港澳台",港台电视32
http://zs178.3322.org:9081/stream/channelid/93183343

#EXTINF:-1 tvg-id="408" tvg-name="ViuTV" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/viutv.png" group-title="港澳台",ViuTV
http://zs178.3322.org:9081/stream/channelid/1496352353
#EXTINF:-1 tvg-id="408" tvg-name="ViuTV" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/viutv.png" group-title="港澳台",ViuTV 6

#EXTINF:-1 tvg-id="408" tvg-name="ViuTV" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/viutv.png" group-title="港澳台",ViuTVsix
http://zs178.3322.org:9081/stream/channelid/1549479758


#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 凤凰资讯
http://iptv.tvfix.org/hls/fhzx.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 凤凰中文
http://iptv.tvfix.org/hls/fhzw.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 凤凰电影(720P)
http://iptv.tvfix.org/hls/fhdy.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Discovery
http://iptv.tvfix.org/hls/discovery.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 动物星球
http://iptv.tvfix.org/hls/animal.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Love Nature
http://iptv.tvfix.org/hls/lovenature4k.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Love Nature(第2声道)
http://iptv.tvfix.org/hls/lovenature4k2.m3u8
#EXTINF:-1 tvg-id="691" tvg-name="" tvg-logo="" group-title="港澳台", 国家地理
http://iptv.tvfix.org/hls/natlgeo.m3u8
#EXTINF:-1 tvg-id="129" tvg-name="" tvg-logo="" group-title="港澳台", TVB经典台
http://iptv.tvfix.org/hls/tvbjd.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", TVB为食台
http://iptv.tvfix.org/hls/tvbws.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", TVB为食台(第2声道)
http://iptv.tvfix.org/hls/tvbws2.m3u8
#EXTINF:-1 tvg-id="131" tvg-name="" tvg-logo="" group-title="港澳台", TVB星河(粤语)
http://iptv.tvfix.org/hls/tvbxh.m3u8
#EXTINF:-1 tvg-id="131" tvg-name="" tvg-logo="" group-title="港澳台", TVB星河(普通话)
http://iptv.tvfix.org/hls/tvbxh2.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", TVB功夫台(粤语)
http://iptv.tvfix.org/hls/tvbkf.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", TVB功夫(普通话)
http://iptv.tvfix.org/hls/tvbkf2.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Thrill(第2声道)
http://iptv.tvfix.org/hls/thrill2.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Thrill
http://iptv.tvfix.org/hls/thrill.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Hands Up Channel(第2声道)
http://iptv.tvfix.org/hls/kid2.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", Hands Up Channel
http://iptv.tvfix.org/hls/kid.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Animax" tvg-logo="" group-title="港澳台", Animax(第2声道)
http://iptv.tvfix.org/hls/animax2.m3u8
#EXTINF:-1 tvg-id="" tvg-name="Animax" tvg-logo="" group-title="港澳台", Animax
http://iptv.tvfix.org/hls/animax.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 天映经典(720P)
http://iptv.tvfix.org/hls/tyjd.m3u8
#EXTINF:-1 tvg-id="145" tvg-name="" tvg-logo="" group-title="港澳台", 美亚高清电影台
http://iptv.tvfix.org/hls/mydy.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 瞬间看地球
http://iptv.tvfix.org/hls/earth.m3u8
#EXTINF:-1 tvg-id="7118" tvg-name="" tvg-logo="" group-title="港澳台", 开电视
http://iptv.tvfix.org/hls/opentv.m3u8
#EXTINF:-1 tvg-id="7117" tvg-name="" tvg-logo="" group-title="港澳台", 国际财經台
http://iptv.tvfix.org/hls/hkibc.m3u8





#EXTINF:-1 tvg-id="7118" tvg-name="香港开电视" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/hongkongkai.png" group-title="港澳台",香港开电视

#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/RTHK.jpg" group-title="港澳台",香港电台
https://rthkcnews-lh.akamaihd.net/i/rthknews_1@312607/index_190000011_av-b.m3u8
#EXTINF:-1 tvg-id="7118" tvg-name="香港开电视" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/hongkongkai.png" group-title="港澳台",开电视
http://livetv.dnsfor.me:80/channel.9.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",香港C+
http://gslbmeiah.cdn.hk.chinamobile.com/livehls/MOB-U1-NO/03.m3u8

#EXTINF:-1 tvg-id="7118" tvg-name="香港开电视" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/hongkongkai.png" group-title="港澳台",香港开电视

#EXTINF:-1 tvg-id="141" tvg-name="凤凰中文" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/fenghuangzhongwen.png" group-title="港澳台",凤凰中文
http://124.238.99.44:808/hls/348/index.m3u8
#EXTINF:-1 tvg-id="142" tvg-name="凤凰资讯" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/fenghuangzixun.png" group-title="港澳台",凤凰资讯
http://39.135.53.199/ott.fj.chinamobile.com/PLTV/88888888/224/3221225901/index.m3u8
#EXTINF:-1 tvg-id="142" tvg-name="凤凰资讯" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/fenghuangzixun.png" group-title="港澳台",凤凰资讯台
http://zb.ios.ifeng.com:80/live/05QGCOB3T34/index.m3u8
#EXTINF:-1 tvg-id="143" tvg-name="凤凰香港" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/fenghuangxianggang.png" group-title="港澳台",凤凰香港
http://223.110.245.136/PLTV/3/224/3221226975/index.m3u8

#EXTINF:-1 tvg-id="476" tvg-name="澳亚卫视" tvg-logo="http://epg.51zmt.top:8000/tb1/gt/澳亚卫视.png" group-title="港澳台",澳亚卫视
http://116.199.5.52:8114/00000000/index.m3u8?&Fsv_ctype=LIVES&Fsv_otype=1&FvSeid=5abd1660af1babb4&Fsv_filetype=1&Fsv_ctype=LIVES&Fsv_cid=0&Fsv_chan_hls_se_idx=192&Fsv_rate_id=0&Fsv_SV_PARAM1=0&Fsv_ShiftEnable=0&Fsv_ShiftTsp=0&Provider_id=&Pcontent_id=&Fsv_CMSID=&Fsv_otype=1
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AP.jpg" group-title="港澳台",澳视葡文
http://live4.tdm.com.mo:80/ch2/_definst_/ch2.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",澳视卫视
http://live4.tdm.com.mo:80/ch3/_definst_/ch3.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="https://gitee.com/feng5know/feng/raw/master/AS.jpg" tvg-logo="" group-title="港澳台",澳视澳门
http://61.244.22.4/ch1/ch1.live/playelist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳视澳门
http://live4.tdm.com.mo/ch1/_definst_/ch1.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳视澳门
http://61.244.22.5/ch1/_definst_/ch1.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳视葡文
http://61.244.22.4/ch2/ch2.live/chunklist_w1632175875.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳视资讯
http://61.244.22.5/ch5/info_ch5.live/master.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo=https://gitee.com/feng5know/feng/raw/master/AS.jpghttps://gitee.com/feng5know/feng/raw/master/AS.jpg"" group-title="港澳台",澳门2台
http://61.244.22.4/ch2/ch2.live/playelist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳门3台
http://61.244.22.4/ch3/ch3.live/playelist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳门-MACAU
http://live4.tdm.com.mo/ch3/_definst_/ch3.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳门卫星
http://61.244.22.5/ch3/_definst_/ch3.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo=https://gitee.com/feng5know/feng/raw/master/AS.jpg"" group-title="港澳台",澳门卫视
http://61.244.22.5/ch3/ch3.live/chunklist_w1228316132.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳门综艺
http://live4.tdm.com.mo/ch6/_definst_/hd_ch6.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳门资讯
http://live4.tdm.com.mo/ch5/_definst_/info_ch5.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/AS.jpg" group-title="港澳台",澳门资讯
http://61.244.22.5/ch5/_definst_/info_ch5.live/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",耀才财经台1
http://202.69.67.66:443/webcast/bshdlive-pc/playlist.m3u8?wowzasessionid=64000
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",耀才财经
http://202.69.67.66:443/webcast/bshdlive-mobile/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",耀才财经
http://202.69.67.66:443/webcast/bshdlive-pc/playlist.m3u8



#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/TY.jpg" group-title="电影",天映频道
http://50.7.161.82:8278/streams/d/Celestial/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/TYJD.jpg" group-title="电影",天映经典
http://50.7.161.82:8278/streams/d/Celestial2/playlist.m3u8
#EXTINF:-1 tvg-id="69" tvg-name="金鹰卡通" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/jinyingkatong.png" group-title="卡通",金鹰卡通
http://183.207.248.71:80/cntv/live1/n-jinyingkaton/n-jinyingkaton
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="https://gitee.com/feng5know/feng/raw/master/XDKT.jpg" group-title="卡通",炫动卡通
http://183.207.248.71:80/cntv/live1/n-xuandongkaton/n-xuandongkaton
#EXTINF:-1 tvg-id="6010" tvg-name="嘉佳卡通" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/jiajiakt.png" group-title="卡通",嘉佳卡通
http://183.207.248.71:80/cntv/live1/SD-4000k-576P-jiajiakaton/SD-4000k-576P-jiajiakaton
#EXTINF:-1 tvg-id="67" tvg-name="卡酷动画" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/kaku.png" group-title="卡通",卡酷少儿
http://183.207.248.71:80/cntv/live1/n-kakukaton/n-kakukaton
#EXTINF:-1 tvg-id="1046" tvg-name="优漫卡通" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/youman.png" group-title="卡通",优漫卡通
http://183.207.248.71:80/cntv/live1/n-youmankaton/n-youmankaton
#EXTINF:-1 tvg-id="6242" tvg-name="求索动物" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/QSDW.jpg" group-title="地方",求索动物
http://39.135.98.8/hwltc.tv.cdn.zj.chinamobile.com/PLTV/88888888/224/3221228980/01.m3u8?fmt=ts2hls
#EXTINF:-1 tvg-id="6240" tvg-name="求索科学" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/QSKX.jpg" group-title="地方",求索科学
http://39.134.66.66/PLTV/88888888/224/3221225728/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/QSJL.jpg" group-title="地方",求索生活
http://39.134.66.66/PLTV/88888888/224/3221225715/index.m3u8
#EXTINF:-1 tvg-id="6244" tvg-name="求索记录" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/QSJL.jpg" group-title="地方",求索记录
http://39.134.66.66/PLTV/88888888/224/3221225713/index.m3u8
#EXTINF:-1 tvg-id="6244" tvg-name="求索记录" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/QSJL.jpg" group-title="地方",求索记录
http://39.134.65.162/PLTV/88888888/224/3221225713/index.m3u8

#EXTINF:-1 tvg-id="1977" tvg-name="欢笑剧场" tvg-logo="http://epg.51zmt.top:8000/tb1/qt/huanxiao.png" group-title="4K频道",欢笑剧场
http://39.134.39.38/PLTV/88888888/224/3221226203/index.m3u8
#EXTINF:-1, tvg-logo=纯享4K.png tvg-name=纯享4K group-title=4K频道, 纯享4K
http://39.135.138.58:18890/PLTV/88888888/224/3221225786/index.m3u8
#EXTINF:-1, tvg-logo=爱上4K.png tvg-name=爱上4K group-title=4K频道, 爱上4K
http://39.134.19.4/dbiptv.sn.chinamobile.com/PLTV/88888888/224/3221226352/1.m3u8
#EXTINF:-1,  tvg-logo=咪咕4K.png tvg-name=咪咕4K group-title=4K频道, 咪咕4K
http://221.179.217.9//otttv.bj.chinamobile.com/PLTV/88888888/224/3221226399/1.m3u8	
#EXTINF:-1,斗鱼4K[3840*2160]
http://epg.112114.xyz/douyu/9249162


#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 民视
http://live.hodtv.tv/gttv.php?id=13669&cid=13822
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台", 華視
http://live.hodtv.tv/gttv.php?id=13676&cid=13829
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",中視
http://live.hodtv.tv/gttv.php?id=13681&cid=13834
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",台視
http://live.hodtv.tv/gttv.php?id=14185&cid=14345

#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",麥卡貝電視
http://live.hodtv.tv/gttv.php?id=11423&cid=11422
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",西洋電影台
http://live.hodtv.tv/gttv.php?id=11425&cid=11425
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",亞洲電影台
http://live.hodtv.tv/gttv.php?id=11426&cid=11426
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",國際電影台
http://live.hodtv.tv/gttv.php?id=13182&cid=13333
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",電影原聲台
http://live.hodtv.tv/gttv.php?id=14188&cid=14348
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",我的歐洲電影
http://live.hodtv.tv/gttv.php?id=14399&cid=14562
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",aMC最愛電影
http://live.hodtv.tv/gttv.php?id=13624&cid=13776
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",影迷數位電影台
http://live.hodtv.tv/gttv.php?id=13695&cid=13848
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",影迷數位紀實台
http://live.hodtv.tv/gttv.php?id=14132&cid=14292
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",CATCHPLAY電影台
http://live.hodtv.tv/gttv.php?id=14181&cid=14341
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",CN卡通頻道
http://live.hodtv.tv/gttv.php?id=13645&cid=13797
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",优電影一台
http://live.hodtv.tv/gttv.php?id=14160&cid=14320
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",优電影二台
http://live.hodtv.tv/gttv.php?id=13657&cid=13809
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="港澳台",优電影三台
http://live.hodtv.tv/gttv.php?id=13658&cid=13810


#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",AXN电影
http://211.23.114.106:8558/http/116.50.42.19:8081/hls/71/813/ch43.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",Cinemax
http://211.23.114.106:8559/http/116.50.42.19:8081/hls/71/813/ch42.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",111
http://50.7.161.82:8278/streams/d/Boo/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",FOXmovies
http://211.23.114.106:8560/http/116.50.42.19:8081/hls/62/804/ch08.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",FOX频道
http://211.23.114.106:8561/http/116.50.42.19:8081/hls/61/803/ch02.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",国家地理
http://211.23.114.106:8509/http/61.221.81.94:8088/hls/61/803/ch01.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",Discovery
http://211.23.114.106:8510/http/61.221.81.94:8088/hls/71/813/ch44.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",旅游生活
http://211.23.114.106:8570/http/61.221.81.94:8088/hls/70/812/ch38.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",动物星球
http://211.23.114.106:8512/http/61.221.81.94:8088/hls/70/812/ch37.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",HBO-综合
http://211.23.114.106:8511/http/116.50.42.19:8081/hls/71/813/ch41.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",STAR MOVIES
http://211.23.114.106:8560/http/116.50.42.19:8081/hls/62/804/ch08.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",HBO
http://198.16.106.62:8278/streams/d/sundance_twn/playlist.m3u8

#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",北京新闻
http://hsplay-360.v.btime.com/live_btime/btv_sn_20170706_s9/index.m3u8?time=
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",凤凰资讯 10M1080
http://223.110.235.13/ott.js.chinamobile.com/PLTV/3/224/3221228098/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外" ,凤凰中文 10M1080
http://223.110.235.3/ott.js.chinamobile.com/PLTV/3/224/3221228057/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外" ,凤凰资讯 10M1080
http://223.110.245.167/ott.js.chinamobile.com/PLTV/3/224/3221226923/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外" ,凤凰香港 10M1080
http://223.110.236.2/ott.js.chinamobile.com/PLTV/3/224/3221228060/index.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外" ,三立台湾
https://setlive-lh.akamaihd.net/i/settaiwan_1@301196/index_1080_av-b.m3u8?sd=10&amp;rebase=on
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外" ,三立都会
https://setlive-lh.akamaihd.net/i/setmetro_1@132201/index_1080_av-b.m3u8?sd=10&amp;rebase=on
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",NHK WORLD TV[1920*1080]
https://nhkwlive-ojp.akamaized.net/hls/live/2003459/nhkwlive-ojp-en/index_4M.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",NHK Chinese Vision[1280*720]
https://nhkw-zh-hlscomp.akamaized.net/8thz5iufork8wjip/playlist.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",KBS World[1024*576][1024*576]
https://livecdn.fptplay.net/sdb/kbs_hls.smil/chunklist_b2500000.m3u8
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" group-title="海外",BBCWorldNews
http://103.199.161.254/Content/bbcworld/Live/Channel(BBCworld)/index.m3u8
